parameters:
  VM_IMAGE: 'ubuntu-latest'
  IMAGE_REPOSITORY: ''
  IMAGE_PULL_SECRET: ''
  DEPLOYMENT_ENVIRONMENT: ''
  DOCKER_REGISTRY_SERVICE_CONNECTION: ''
  AZURE_CONTAINER_REGISTRY: ''
  DOCKER_FILE_PATH: ''
  IMAGE_TAG: 'latest'
jobs:    
- deployment: Deploy
  displayName: Deploy
  pool:
    vmImage: ${{parameters.VM_IMAGE}}
  environment: ${{parameters.DEPLOYMENT_ENVIRONMENT}}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: KubernetesManifest@0
          displayName: Create imagePullSecret
          inputs:
            action: createSecret
            secretName: ${{parameters.IMAGE_PULL_SECRET}}
            dockerRegistryEndpoint: ${{parameters.DOCKER_REGISTRY_SERVICE_CONNECTION}}
        
        - task: KubernetesManifest@0
          displayName: Deploy to Kubernetes cluster
          inputs:
            action: deploy
            manifests: |
              $(Pipeline.Workspace)/manifests/deployment.yml
              $(Pipeline.Workspace)/manifests/service.yml
            imagePullSecrets: |
              ${{parameters.IMAGE_PULL_SECRET}}
            containers: |
              ${{parameters.AZURE_CONTAINER_REGISTRY}}/${{parameters.IMAGE_REPOSITORY}}:${{parameters.IMAGE_TAG}}